// Each entry is a different activity, not a title variant of the same walk.
// Budgets include getting outside and returning; no remote destination is assumed.
const groups = {
  movement: [
    ["gentle-walk", "A Little Reset", 5, 12, "Walk a familiar public route at an easy pace. Notice one detail before turning back."],
    ["brisk-loop", "A Brisk Familiar Loop", 10, 20, "Walk a familiar loop at a comfortable brisk pace. Slow down whenever needed.", { physical: "medium" }],
    ["pace-ladder", "Change the Pace", 10, 20, "Alternate one minute of comfortable brisk walking with two easy minutes on a familiar flat route.", { physical: "medium" }],
    ["outdoor-mobility", "An Outdoor Mobility Break", 5, 10, "In a quiet public spot, gently move your shoulders, wrists and ankles through a comfortable range. Stop if anything hurts."],
    ["bench-reset", "Walk, Sit, Walk", 10, 20, "Walk to a bench you already know is close by. Sit briefly, then walk home; turn back early if no seat is available."],
    ["posture-stroll", "A Comfortable Stride", 5, 12, "Take an easy walk and notice your posture. Relax your shoulders without forcing a position."],
    ["companion-loop", "Walk With Someone", 15, 30, "Invite someone you know for a short familiar loop. If they are unavailable, enjoy the loop alone.", { social: "low" }],
    ["jog-walk", "A Gentle Jog-Walk", 15, 25, "If jogging is already comfortable for you, alternate short easy jogs with walking on a familiar route. Walking throughout is fine.", { physical: "high" }],
    ["standing-pause", "Stand in the Open Air", 5, 8, "Stand or sit outside your building in an accessible spot. Let your eyes rest on the surroundings."],
    ["rhythm-walk", "Find Your Walking Rhythm", 5, 15, "On a familiar pavement, count a few comfortable steps in groups of four, then stop counting and enjoy your natural rhythm."],
    ["ball-practice", "A Little Ball Practice", 10, 20, "In a permitted open space close to home, gently dribble or practise controlled passes with a ball. Keep clear of traffic and other people.", { physical: "medium", prep: ["Bring a ball you already own."] }],
    ["heel-raises", "A Supported Movement Pause", 5, 10, "At a stable support outdoors, try a few slow heel raises if comfortable. Keep both feet on the ground instead if balance is uncertain.", { physical: "medium" }],
    ["shade-loop", "Follow the Shady Side", 5, 15, "Choose the shaded side of a familiar pedestrian route. Turn around before half your time is used."],
    ["park-lap", "One Familiar Park Lap", 15, 25, "If a park you know is within a short walk, take one easy lap on its public path. Otherwise use your usual route."],
    ["cycling-reset", "A Short Familiar Ride", 20, 30, "If you already cycle confidently, ride a short known permitted route and return. Skip unsafe traffic or poor visibility.", { physical: "high", daylight: true, dry: true, prep: ["Use your own bike and helmet; check brakes before leaving."] }],
    ["dry-ground-stretch", "A Gentle Outdoor Stretch", 5, 12, "In a safe dry spot outdoors, do a few stretches you already know. Stay within a comfortable range and do not force movement.", { dry: true }],
    ["talk-pace", "A Conversation-Pace Walk", 10, 20, "Walk at a pace where speaking a sentence feels comfortable. Ease off when needed rather than chasing a distance."],
    ["balance-supported", "A Supported Balance Moment", 5, 8, "Beside a secure railing in a quiet outdoor spot, practise standing evenly on both feet. Only try a brief one-foot lift if it is already safe for you.", { dry: true }],
    ["new-turn", "One Different Turn", 10, 20, "On your familiar walking route, try one different public turn with clear visibility. Retrace your steps before half your time is gone."],
    ["finish-easy", "An Easy Finish", 10, 20, "Walk comfortably on a familiar route and make the final few minutes slower. Notice how your pace changes."],
  ],
  nature: [
    ["nature-noticing", "Notice Something Growing", 5, 10, "Observe a plant or tree from a public space. Notice its shape and one detail without touching or picking it."],
    ["leaf-shapes", "A Leaf Shape Safari", 5, 12, "Find three different leaf shapes from a public path. Compare their outlines without picking leaves."],
    ["bird-listening", "Listen for Birds", 5, 12, "Stand or sit quietly outside and listen for different bird calls. No identification is required; keep your distance from wildlife."],
    ["cloud-study", "Read the Clouds", 5, 10, "From a safe stationary spot, watch clouds drift and look for changing shapes. Do not look directly at the sun.", { daylight: true }],
    ["tree-bark", "A Tree's Surface", 5, 10, "Observe the bark of a tree from a public path. Compare smooth areas, ridges and colour without scraping it."],
    ["insect-watch", "A Tiny Wildlife Watch", 10, 15, "Observe a small patch of planting from a safe distance. Look for insects without handling them or disturbing nests.", { daylight: true }],
    ["fallen-leaf", "A Fallen Leaf Story", 5, 8, "Look at a fallen leaf where it lies. Notice wear, veins and colour, then leave it in place."],
    ["bird-movement", "Watch How Birds Move", 5, 12, "Watch a bird from a respectful distance. Notice how it walks, perches or flies; never feed or follow it."],
    ["wind-in-trees", "Trace the Wind", 5, 10, "Watch how leaves or grasses move in the breeze from a sheltered public spot. Compare still and moving areas."],
    ["flower-observe", "A Flower Close-Up", 5, 10, "Observe one flower from a public path. Count visible petals if you can, without picking or leaning into planting."],
    ["tree-canopy", "Under a Canopy", 10, 15, "From a safe path near a tree, look at how branches form its canopy. Stay away from damaged trees and falling branches.", { daylight: true }],
    ["nature-sound-map", "A Nature Sound Map", 5, 12, "From a stationary outdoor spot, notice where natural sounds seem to come from. Make a simple mental map."],
    ["rain-afterwards", "After-Rain Details", 5, 12, "If rain has stopped and the path is safe, observe droplets and puddle reflections without stepping into puddles. Otherwise notice dry surfaces.", { daylight: true }],
    ["season-signs", "Find a Seasonal Clue", 5, 15, "Look for a sign of the local season: new growth, dry leaves, flowers or changing light. Do not assume it matches another region."],
    ["grass-observation", "A Small Patch of Green", 5, 10, "Look at a patch of grass or ground cover from the path. Notice how many shades and heights you can see."],
    ["tree-silhouettes", "Tree Silhouettes", 5, 12, "Compare the outlines of two trees from a public spot. Notice broad, narrow or branching shapes.", { daylight: true }],
    ["nature-quiet-seat", "A Quiet Green Pause", 10, 20, "Use a familiar accessible seat near planting, if available. Spend a few minutes noticing movement around you before returning."],
    ["seed-heads", "Seeds Without Collecting", 5, 12, "Look for seed heads or pods in public planting. Observe them in place; do not taste, collect or handle unfamiliar plants."],
    ["sky-colours", "A Sky Colour Check", 5, 10, "Observe the colours of the sky from a stationary spot. Keep your eyes away from the sun.", { daylight: true }],
    ["familiar-tree-return", "Meet a Familiar Tree Again", 10, 20, "Revisit a tree on a route you already know. Notice one detail that has changed or that you missed before."],
  ],
  curiosity: [
    ["texture-hunt", "Three Textures", 5, 10, "Find three visually different textures on your familiar route. Avoid touching unfamiliar objects or entering private areas."],
    ["colour-collection", "A Colour Collection", 5, 15, "Find three colours outdoors and remember your favourite combination."],
    ["sign-typography", "Street Lettering", 5, 12, "Compare lettering on two public signs. Notice shapes and spacing while standing safely off the path."],
    ["building-era", "Architecture Detective", 10, 20, "Compare two building facades from a public pavement. Look for materials or details suggesting different eras, without treating guesses as facts."],
    ["number-hunt", "Numbers in the Neighbourhood", 5, 10, "Spot five different numbers on public signs. Do not photograph private addresses or people's personal details."],
    ["sound-layers", "Three Layers of Sound", 5, 10, "From a stationary spot, notice one nearby, one medium-distance and one faraway sound."],
    ["public-art", "An Art Detail", 10, 20, "Look for public artwork or an interesting design on a familiar route. If none is present, study a public sign as design."],
    ["route-memory", "Remember the Route", 10, 15, "On a familiar short route, pick three public landmarks. Recall their order on your way back without needing a screen."],
    ["shadow-patterns", "Shadow Patterns", 5, 12, "Find interesting shadows from railings, trees or buildings. Observe from a safe stationary spot.", { daylight: true }],
    ["doorway-design", "Doorway Details", 5, 12, "Notice how doors and entrances differ along a public street. Stay on the pavement and respect residents' privacy."],
    ["street-history", "A Public Plaque", 10, 20, "Read a public plaque or information board you already know nearby. If none is available, notice a street name and wonder about its origin."],
    ["pattern-count", "Repeating Patterns", 5, 10, "Find a repeating pattern in paving, fencing or windows. Count a small section while stationary."],
    ["scent-noticing", "An Outdoor Scent Check", 5, 8, "Notice ambient scents in an open public spot without approaching smoke, chemicals or unfamiliar plants."],
    ["accessibility-observe", "Notice an Accessible Detail", 10, 15, "Observe public ramps, crossings or seating on a familiar route. Notice a helpful design without assuming it works for every person."],
    ["transport-observe", "How a Street Moves", 5, 12, "From a safe stationary pavement spot, notice the different ways people travel. Do not record faces or licence plates."],
    ["window-reflections", "A Reflection Hunt", 5, 10, "Find a reflection in a public window or puddle. Observe from the path without photographing interiors or private spaces."],
    ["street-materials", "What Is This Street Made Of?", 5, 12, "Identify visually different materials along your route, such as brick, stone and metal. Leave unfamiliar surfaces untouched."],
    ["tiny-landmark", "Find a Tiny Landmark", 5, 15, "Notice a small public detail you usually pass by. Give it a memorable nickname in your head."],
    ["before-after-route", "Same Route, New Perspective", 10, 20, "Walk a familiar short route and notice how it looks in the opposite direction on your return."],
    ["community-board", "Read the Community Board", 10, 20, "Read a noticeboard you already know is publicly accessible nearby. Do not assume listed events are current without checking their dates."],
  ],
  creativity: [
    ["outdoor-sketch", "A Tiny Outdoor Sketch", 5, 12, "Sketch one ordinary outdoor object from a safe stationary spot close to home.", { prep: ["Bring paper and a pencil."] }],
    ["outdoor-reading", "A Few Pages Outside", 5, 15, "Read a few pages at a familiar accessible outdoor spot close to home.", { prep: ["Bring a book."] }],
    ["three-line-poem", "A Three-Line Outdoor Poem", 5, 10, "Look at one outdoor detail and make three short lines about it. Remember them or jot them on paper."],
    ["mental-photo", "Take a Mental Photograph", 5, 10, "Frame a small outdoor scene with your attention, not a camera. Look away and recall three details."],
    ["one-line-drawing", "One-Line Drawing", 5, 12, "Draw an outdoor object without lifting your pencil, from a stationary public spot.", { prep: ["Bring paper and a pencil."] }],
    ["sound-poem", "Write the Soundscape", 5, 12, "Turn three sounds you hear outdoors into words or rhythms. Keep it private rather than performing to passersby."],
    ["colour-palette", "An Outdoor Colour Palette", 5, 12, "Choose four colours you see outside and imagine them as a palette for a room, outfit or painting."],
    ["object-story", "An Ordinary Object's Story", 5, 12, "Invent a short fictional story about a public bench, lamp or sign. Do not make up stories about identifiable strangers."],
    ["sky-journal", "A Sky Journal Entry", 5, 10, "From a stationary spot, describe today's sky in a few words on paper. Keep your eyes away from the sun.", { daylight: true, prep: ["Bring a notebook and pencil."] }],
    ["postcard-home", "A Postcard From Your Street", 10, 15, "Write a short postcard-style description of your own neighbourhood while sitting or standing safely outside.", { prep: ["Bring paper and a pencil."] }],
    ["shape-composition", "Compose With Shapes", 5, 12, "Find a triangle, circle and rectangle in a public outdoor scene. Imagine arranging them into a picture."],
    ["shadow-sketch", "Sketch a Shadow", 5, 12, "Draw the outline of a shadow on paper without marking public surfaces.", { daylight: true, prep: ["Bring paper and a pencil."] }],
    ["six-word-story", "A Six-Word Street Story", 5, 10, "Make a six-word story inspired by a place or object you see outside."],
    ["texture-drawing", "Draw a Texture", 5, 12, "Observe bark, brick or paving and draw its texture on paper. Do not make rubbings or touch fragile surfaces.", { prep: ["Bring paper and a pencil."] }],
    ["outdoor-letter", "A Letter in the Open Air", 10, 20, "At a familiar quiet outdoor spot, write a kind note to someone you know. Sending it later is optional.", { prep: ["Bring paper and a pencil."] }],
    ["scene-memory-sketch", "Draw From Outdoor Memory", 10, 15, "Study a small outdoor scene, then face away and sketch what you remember from a safe stationary spot.", { prep: ["Bring paper and a pencil."] }],
    ["nature-metaphor", "Find a Fresh Metaphor", 5, 10, "Notice a natural detail outside and compare it to something unexpected. Keep one sentence you like."],
    ["architecture-sketch", "An Entrance in Five Lines", 5, 12, "Sketch a public-facing entrance using just five lines. Stay on the pavement and leave space for others.", { prep: ["Bring paper and a pencil."] }],
    ["silent-melody", "An Outdoor Melody", 5, 12, "Sit or stand outside and imagine a short melody inspired by the rhythm around you. No recording or public performance needed."],
    ["paper-viewfinder", "A Paper Viewfinder", 5, 12, "Use a small opening in scrap paper to frame an outdoor scene while stationary. Notice how the composition changes.", { prep: ["Prepare a small opening in scrap paper before leaving."] }],
  ],
  social: [
    ["neighbour-hello", "One Small Hello", 5, 8, "On your usual walk, greet someone if a natural opportunity arises. Respect their space and accept no response."],
    ["friend-invite", "Invite a Friend Outside", 10, 20, "Invite someone you know for a nearby outdoor pause. If unavailable, go out briefly yourself; no pressure to join."],
    ["known-person-chat", "A Familiar Face Check-In", 10, 15, "If you meet someone you already know outdoors, ask how their day is going. Keep it brief if they seem busy."],
    ["thank-worker", "A Genuine Thank You", 5, 12, "If a worker helps you during a normal outdoor errand, thank them specifically. Do not interrupt someone just to complete a quest."],
    ["family-stroll", "A Family Stroll", 15, 25, "Invite a family or household member to walk a familiar route. Let them choose whether to join."],
    ["shared-detail", "Share One Interesting Detail", 10, 15, "With a willing companion outdoors, point out one small detail you noticed and ask what caught their eye."],
    ["listen-without-phone", "An Undistracted Conversation", 10, 20, "With someone you know outdoors, put your phone away and listen to a short story from their day."],
    ["companion-route-choice", "Let Someone Choose the Turn", 10, 20, "On a walk with a willing familiar companion, let them choose a safe public turn within your shared time budget."],
    ["shop-question", "Ask One Useful Question", 10, 20, "During an errand at a familiar shop, ask a genuine practical question if staff are available. Do not invent a reason to interrupt them."],
    ["neighbour-help-offer", "Offer a Small Hand", 10, 15, "If a neighbour you know has an obvious ordinary task outdoors, offer help once. Accept a decline and avoid unsafe lifting or tools."],
    ["community-date-check", "Find a Local Gathering Date", 10, 20, "Check a familiar public noticeboard for a future gathering you might enjoy. Verify the date before making plans."],
    ["walk-with-question", "A Walk and a Good Question", 15, 25, "Ask a willing familiar walking companion about something they have enjoyed recently. Give them space to answer."],
    ["shared-quiet", "Company Without Conversation", 10, 20, "Invite someone you know to sit or walk outside quietly together. Agree that talking is optional."],
    ["kind-compliment", "A Thoughtful Compliment", 5, 10, "If a natural moment arises with someone you know outdoors, offer a genuine compliment about something they did, not their appearance."],
    ["ask-local-tip", "Ask for a Local Tip", 10, 15, "Ask a familiar neighbour for a public place they enjoy nearby, if they have time. Treat it as a suggestion to verify later."],
    ["outdoor-card-game", "A Small Outdoor Game", 15, 30, "With a willing friend, play a short card game at a familiar outdoor table. Leave the space tidy.", { prep: ["Bring a deck of cards."] }],
    ["shared-book-passage", "Share a Favourite Passage", 10, 20, "With a willing friend outdoors, share a short passage from a book and ask what they think.", { prep: ["Bring a book you already own."] }],
    ["companion-gratitude", "Thank Your Walking Companion", 10, 15, "On a short walk with someone you know, tell them one specific thing you appreciate. No response is required."],
    ["courteous-space", "Make Room for Someone", 5, 10, "On a familiar walk, practise ordinary courtesy: leave room on the path and let others pass without forcing an interaction.", { social: "none" }],
    ["next-walk-plan", "Plan the Next Walk Together", 10, 20, "During a short outdoor catch-up with someone you know, suggest a possible future walk. Keep the plan optional."],
  ],
  errand: [
    ["practical-check", "Tomorrow's Small Errand", 5, 10, "On your familiar route, check one useful posted detail such as a shop's hours. No purchase required."],
    ["essential-top-up", "One Essential Top-Up", 10, 20, "If you already need a basic item and know a nearby shop, walk there to check availability. Skip the purchase if unsuitable.", { prep: ["Bring your existing shopping list and a reusable bag."] }],
    ["pantry-list-walk", "A Pantry List Walk", 5, 12, "Before leaving, note one missing pantry item. On a short familiar walk, decide whether it belongs on your next shopping list."],
    ["recycling-drop", "A Recycling Drop", 10, 20, "Take suitable household recycling to a collection point you already know is nearby and accepts it. Bring it home if unavailable.", { prep: ["Check accepted materials and carry clean household recycling."] }],
    ["letter-post", "Post a Ready Letter", 10, 20, "If you have a prepared letter and know a nearby postbox, walk there and check the posted collection details.", { prep: ["Bring an addressed letter with appropriate postage."] }],
    ["library-return", "Return a Library Book", 15, 30, "If a library you use is already within your time budget, walk to return a borrowed book. Check actual access on arrival.", { prep: ["Bring the borrowed book; use only a library you already know nearby."] }],
    ["donation-plan", "Plan a Donation Drop", 10, 20, "Check posted details at a donation point you already know nearby. Verify accepted items before bringing anything later."],
    ["repair-shop-check", "Find a Repair Option", 10, 20, "On a familiar route, check a known repair shop's posted services for an item you already own. Do not assume price or availability."],
    ["refill-check", "A Refill Possibility", 10, 20, "Check whether a familiar local shop advertises refills for something you use. Ask only if staff are free; purchase is optional."],
    ["market-list", "A Market List Check", 10, 20, "If you already know a nearby market, compare its public displays with your existing needs. No purchase required."],
    ["home-measure-plan", "A Home Fix Reconnaissance", 10, 20, "For a small home item you already need, check a familiar nearby hardware shop's posted hours. Measure the item at home before a later purchase."],
    ["price-compare", "Compare One Needed Item", 10, 20, "At a shop you already know nearby, check the displayed price of one item on your list. Do not buy just to complete the quest."],
    ["water-bottle-walk", "Prepare Tomorrow's Bottle", 5, 10, "Fill your reusable bottle at home, then take a short outdoor walk. Notice whether it is comfortable to carry for tomorrow."],
    ["shoe-repair-check", "Give Your Shoes Another Life", 10, 20, "If you know a nearby shoe-repair shop, check its posted services on a short walk. Verify cost and opening before arranging work."],
    ["parcel-return-plan", "A Parcel Return Check", 10, 20, "If you already have a return to arrange, check a known nearby drop-off's posted details. Do not assume it supports your carrier."],
    ["local-menu-check", "Check a Local Menu", 10, 15, "On a familiar route, read an openly posted menu to plan a future meal within your budget. No purchase required."],
    ["bag-readiness", "Test Your Errand Bag", 5, 10, "Take your reusable bag on a short familiar walk and check whether it is comfortable. Do not add purchases for the sake of the task.", { prep: ["Bring an empty reusable bag."] }],
    ["safe-litter-pick", "A Small Tidy-Up", 5, 12, "Only if safe and permitted, pick up a few ordinary dry wrappers near home. Never handle glass, sharps, liquids or unknown waste.", { daylight: true, prep: ["Use gloves and a litter picker; use a suitable bin and wash hands afterward."] }],
    ["public-bin-check", "Locate a Useful Public Bin", 5, 10, "On a familiar route, notice the location and labels of a public waste or recycling bin. Do not handle its contents."],
    ["errand-route-rehearsal", "Rehearse a Useful Walking Route", 10, 20, "Walk part of a familiar pedestrian route for a future errand. Notice crossings and turn back before half your time is used."],
  ],
};

export const ACTIVITY_CATALOG = Object.entries(groups).flatMap(([type, entries]) => entries.map(
  ([id, title, minMinutes, maxMinutes, action, options = {}]) => ({
    id, title, type, minMinutes, maxMinutes, action,
    physical: options.physical || "low", social: options.social || (type === "social" ? "low" : "none"),
    daylight: Boolean(options.daylight), dry: Boolean(options.dry), prep: options.prep || []
  })
));
